// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxrDMI46jbLJzwBfHLjsbfdToUZHjTig',
    appId: '1:108839768198:web:9ddfc77cfd3755742d8107',
    messagingSenderId: '108839768198',
    projectId: 'learning-flutter-video',
    authDomain: 'learning-flutter-video.firebaseapp.com',
    storageBucket: 'learning-flutter-video.appspot.com',
    measurementId: 'G-QMDH55ET7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAedtakeVinoz3aP6FNJkSJHSFU_6Ea3c',
    appId: '1:108839768198:android:a354c25644a45f4f2d8107',
    messagingSenderId: '108839768198',
    projectId: 'learning-flutter-video',
    storageBucket: 'learning-flutter-video.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVID-V5__hX81S34gAUJPDMguPc0ii64',
    appId: '1:108839768198:ios:e01b07871ff9f9bb2d8107',
    messagingSenderId: '108839768198',
    projectId: 'learning-flutter-video',
    storageBucket: 'learning-flutter-video.appspot.com',
    iosClientId: '108839768198-evq8qhhgbhhakgk97pnmtt5nl32k1cmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHVID-V5__hX81S34gAUJPDMguPc0ii64',
    appId: '1:108839768198:ios:b64995078a75e64a2d8107',
    messagingSenderId: '108839768198',
    projectId: 'learning-flutter-video',
    storageBucket: 'learning-flutter-video.appspot.com',
    iosClientId: '108839768198-4sgq0p9567c45haiahd9e8f1b6tc780f.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningFlutterFirebase.RunnerTests',
  );
}
